# Buoyancy Calculations

## Test configuration 1, small particle oil in water

In [1]:
%matplotlib widget

import numpy as np
import matplotlib.pyplot as plt

In [2]:
d = 0.0005
orho = 858.0
wrho = 998.2071
delrho = orho - wrho
wvisc = 1305.90172775e-6
visc = 1.308767294838539e-03
g = -9.8
sigma = 0.023

In [3]:
# ND
nd = 4.0 * wrho * delrho * g * d**3 / (3 * visc**2)
nd

133.45677288001536

In [4]:
# Reynolds Number
logR = -1.7095 + 1.33438 * np.log10(nd) - 0.11591 * np.log10(nd)**2
R = 10**logR
R

4.008095982211944

In [5]:
# Terminal Velocity
UT = R * visc / (wrho * d)
UT

0.010510173562365449

In [6]:
# Morton number
M = g * visc**4 * delrho / (wrho**2 * sigma**3)
M

3.3252247175369584e-10

In [7]:
# Eotovos numbers
E05 = g * delrho * d**2 / sigma
E05

0.01493510413043478

In [8]:
# Eotovos numbers
E015 = g * delrho * 0.015**2 / sigma
E015

13.441593717391305

In [9]:
# Diameter from H
EO  = 3/4 * 59.3 * M**0.149 * (visc/wvisc)**0.14
dH = np.sqrt(EO / (g * delrho) * sigma)
dH

0.005368663147596897

In [10]:
temp = g * delrho * dH**2 / sigma
4/3 * temp * M**-0.149 * (visc / wvisc)**-0.14

59.299999999999976

In [11]:
# Critical Diameter

a1 = 0.5
b1 = np.log10(0.711 * np.sqrt(g * delrho / wrho))

x1 = np.log10(dH)
y1 = np.log10(visc / (wrho * dH) * M**-0.149 * (0.94*59.3**0.757 - 0.857))

x2 = np.log10(0.015)
H2 = 4/3 * E015 * M**-0.149 * (visc/wvisc)**-0.14
y2 = np.log10(visc / (wrho * 0.015) * M**-0.149 * (3.42 * H2**0.441 - 0.857))

a2 = (y2 - y1) / (x2 - x1)
b2 = y1 - a2 * x1

dc = 10**((b2 - b1) / (a1 - a2))
dc

0.01798749114892274

## Ellipsoid Particle, 10 mm

In [12]:
EO10 = g * delrho * 0.01**2 / sigma
EO10

5.974041652173913

In [13]:
H10 = 4/3 * EO10 * M**-0.149 * (visc/wvisc)**-0.14
J = 3.42 * H10**0.441
visc / (wrho * 0.01) * M**-0.149 * (J - 0.857)

0.11846135362594433

## Spherical Cap Particle, 20 mm

In [14]:
EO20 = g * delrho * 0.02**2 / sigma
EO20

23.89616660869565

In [15]:
0.711 * np.sqrt(g * 0.02 * delrho / wrho)

0.11797019910948671

# Barycentric Coordinates

In [16]:
a = np.array((-89.4717160000, 30.0866470000, 3.0000000000))
b = np.array((-89.4966660000, 30.0901150000, 3.9491493700))
c = np.array((-89.4889400000, 30.0744220000, 1.9666023300))
p = np.array((c[0] + 0.1 * (a[0] - b[0]), c[1] + 0.5 * (b[1] - c[1]), 4))
p

array([-89.486445 ,  30.0822685,   4.       ])

In [17]:
plt.scatter(a[0], a[1], label='A')
plt.scatter(b[0], b[1], label='B')
plt.scatter(c[0], c[1], label='C')
plt.scatter(p[0], p[1], label='P')
plt.legend()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
pq = np.array((0, 0, 1))
pa = a - p
pb = b - p
pc = c - p

In [19]:
u = np.dot(np.cross(pq, pc), pb)
u

-9.977609399998197e-05

In [20]:
v = np.dot(np.cross(pq, pa), pc)
v

-0.00010464674100002578

In [21]:
w = np.dot(np.cross(pq, pb), pa)
w

-0.00016032374700008492

In [22]:
denom = u + v + w
denom

-0.00036474658200009264

In [23]:
bc = np.array((u/denom, v/denom, w/denom))
bc

array([0.27354909, 0.2869026 , 0.43954832])

In [24]:
sum(bc)

1.0

In [25]:
q = bc[0] * a + bc[1] * b + bc[2] * c
q

array([-89.486445  ,  30.0822685 ,   2.81808521])

In [26]:
p

array([-89.486445 ,  30.0822685,   4.       ])

In [27]:
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(*a, color='black')
ax.scatter(*b, color='black')
ax.scatter(*c, color='black')
ax.scatter(*p, color='red')
ax.scatter(*q, color='blue')

ax.add_collection3d(Poly3DCollection([a, b, c], alpha=0.25))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [28]:
998 * bc[0] + 1005 * bc[1] + 1010 * bc[2]

1005.2828979957392